### ISSUE TITLE
Issues on responsive degisn and functionality

### ISSUE THREAD

**Issue by amirnsamimi** [zinehzi/portfolio#1]
## Tasks needs to be revised 
- please check your overlayer social media division. 
- double check your viewport fit, env safe padding implementation. 
- recommendation: you can add sticky value to your navigation bar.
- revise your portfolio page and handle images and text-overflows better.
- handling state of drop down is important while you select a page
- effects and smooth behaviors can be change your life if added
- form integration issues ( your form is not working )

**Comment by zinehzi** [comment]
Thank you Amir for taking the time and your comments are very valuable to me
Wish you luck
